### ISSUE TITLE
SelfUpdateCommand.php does not use proxy settings in the stream context

### ISSUE THREAD

**Issue by wesleymusgrove** [consolidation/self-update#10]
I'm behind a proxy and the `self-update` command breaks because it does not take my proxy environment variables into consideration when checking github for the latest release in this file: https://github.com/consolidation/self-update/blob/ed68ed69a427a03bb6fd2197e6d3d564a5ce0cba/src/SelfUpdateCommand.php#L55

Specifically I'm getting this error when trying to `self-update` Acquia CLI:
```
PHP Warning:  file_get_contents(https://api.github.com/repos/acquia/cli/releases): failed to open stream: Connection refused
in phar:///usr/local/bin/acli/vendor/consolidation/self-update/src/SelfUpdateCommand.php on line 70

Warning: file_get_contents(https://api.github.com/repos/acquia/cli/releases): failed to open stream: Connection refused in phar:///usr/local/bin/acli/vendor/consolidation/self-update/src/SelfUpdateCommand.php on line 70

In SelfUpdateCommand.php line 74:

  API error - no release found at GitHub repository acquia/cli

self:update [--stable] [--preview]
```

I think something needs to be added to check for proxy settings and apply them to the stream context, if necessary, but I'm not quite sure how to access proxy settings in this script:
```
$opts = [
            'http' => [
                'method' => 'GET',
                'proxy' => $proxy_environment_variable,
                'header' => [
                    'User-Agent: ' . $this->applicationName  . ' (' . $this->gitHubRepository . ')' . ' Self-Update (PHP)'
                ]
            ]
        ];
```

**Comment by danepowell** [comment]
Seems like Symfony handles proxy variables natively: https://symfony.com/doc/current/http_client.html#http-proxies

Maybe this package should be using the Symfony Http Client instead of handling its own stream context. Otherwise it would need to copy whatever Symfony is doing under the hood.

**Comment by danepowell** [comment]
@codegain @wesleymusgrove I know I'm a little late to the party, but if this still impacts you could you please test https://github.com/consolidation/self-update/pull/33
