### ISSUE TITLE
Drop support for outdated Symfony versions

### ISSUE THREAD

**Issue by mbrodala** [consolidation/self-update#29]
While working on https://github.com/consolidation/self-update/issues/27 I noticed that a lot of old/ancient Symfony versions are still supported.

So maybe consider dropping support for anything which does not get [updates/support from Symfony](https://symfony.com/releases#maintained-symfony-branches) itself anymore. (Currently down to 5.4)

**Comment by greg-1-anderson** [comment]
See also https://github.com/consolidation/self-update/pull/28#issuecomment-1898667119
