### ISSUE TITLE
Support stable/unstable channels

### ISSUE THREAD

**Issue by danepowell** [consolidation/self-update#4]
Most CLIs with self-update capability have the concept of stability channels, i.e. with composer: `composer self-update --preview` vs `composer self-update --stable`

I would be nice to at least support an `--allow-unstable` option so that users on a stable release don't accidentally self-update to an unstable release. The only challenge here is that it requires parsing more than just the most recent available release, to cover the case where there's a new stable update available but an even newer unstable release.

If you're open to the idea, let me know and I can take a crack at a PR. I'd also like to split the business logic into a library separate from the command so that a downstream application could perform update checks without invoking the whole command, let me know if you're okay with this and would prefer the same or a separate PR.

**Comment by greg-1-anderson** [comment]
Should be fixed in 2.0.0-alpha1. Please review and see if use cases are all covered; there is still a little time to submit PRs before we make a stable release.
