### ISSUE TITLE
Add public methods to get latest version and check if phar is up to date

### ISSUE THREAD

**Issue by grasmash** [consolidation/self-update#8]
As a developer, I'd like to use the Self Update library to know if my current phar is already up to date and to know the current version. E.g.,

```
$self_update_command = $this->application->find('self-update');
if (!$self_update_command->isUpToDate()) {
  $latest_version = $self_update_command->getLatestReleaseFromGithub();
  // ... do other things.
}
```

**Comment by danepowell** [comment]
@greg-1-anderson just a heads up, I'm going to work on a PR for this, then combine that with all of the Symfony work I just merged for a v3 beta release.

**Comment by greg-1-anderson** [comment]
It seems odd to me to make command files also be an API for applications to use. A better model would be to add a self update API object, and have the self update command use that.

I have no real objection if you want to go ahead and do it the way the OP suggested, though.

**Comment by danepowell** [comment]
Good point, I'll definitely consider moving the business logic to a standalone class
