### ISSUE TITLE
Don't assume API releases are ordered

### ISSUE THREAD

**Issue by danepowell** [consolidation/self-update#9]
This package calls the Github releases API, and then just pops the first release from the list and assumes it's the latest release. Turns out this fails sometimes, because there's not a documented order for the Github releases API, and the releases aren't always ordered as you'd expect.

I've been able to infer that the releases are ordered by when the release was first created, _including drafts_. This leads to unexpected behavior in a situation such as:
1. You publish version 1.0.
2. You draft version 2.0.
3. You publish a hotfix 1.1.
4. You publish version 2.0.

In this case, self-update would never update users to 2.0, because the GH release API would return 1.1 at the top of the list since it was the most recently created (though not the most recently published).

A real world example here (note how 1.7.2 is higher in the list than 1.8.0): https://api.github.com/repos/acquia/cli/releases

This package should either return all releases and sort them locally to find the true latest release, or use the "latest release" endpoint which does seem to choose the "latest" release correctly.

**Comment by danepowell** [comment]
This is fixed by https://github.com/danepowell/self-update/pull/3 , however that is going to create merge conflicts with https://github.com/consolidation/self-update/pull/5 so I can't contribute it until https://github.com/consolidation/self-update/pull/5 is merged.

**Comment by greg-1-anderson** [comment]
Should be fixed in 2.0.0-alpha1. Please review and see if use cases are all covered; there is still a little time to submit PRs before we make a stable release.

**Comment by danepowell** [comment]
Yep, I agree this is fixed via https://github.com/consolidation/self-update/commit/0c17952fc9ba4d94fa02fb1e9a50f513a72bbede#diff-3419d2e577f48a23aaa66c335786d2ffb493806eac84eef2354c8da33586cdf3R88

Specifically, via our implementation of `Semver::rsort`
